sonar.projectKey=sistema-mensajeria-segura
sonar.projectName=Sistema de Mensajeria Segura
sonar.projectVersion=fase1
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.exclusions=src/frontend/node_modules/**,src/frontend/dist/**,src/**/__pycache__/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
