sonar.projectKey=sistema-mensajeria-segura
sonar.projectName=Sistema de Mensajeria Segura
sonar.projectVersion=fase2
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests,src/frontend/tests
sonar.test.inclusions=tests/**,src/frontend/tests/**
sonar.exclusions=src/frontend/node_modules/**,src/frontend/dist/**,src/frontend/tests/**,src/**/__pycache__/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=artifacts/fase2/coverage.xml
sonar.sarifReportPaths=artifacts/fase2/semgrep.sarif
sonar.host.url=http://localhost:9000
